name: rounded_avatar
description: "RoundedAvatar is a customizable Flutter widget for rounded avatars, supporting network and local images, including SVGs, with border customizations and more options."
version: 1.0.1
homepage: https://github.com/joukhar/flutter_packages
repository: https://github.com/joukhar/flutter_packages

environment:
  sdk: '>=3.4.1 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.10+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
