name: rounded_avatar
description: "The RoundedAvatar package provides a customizable widget for displaying rounded avatars in Flutter applications. It supports both network and local images, including SVGs, and offers various customization options such as border color, border width, border radius, and image fit."
version: 1.0.0
homepage:

environment:
  sdk: '>=3.4.1 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.10+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
